# Generated by Django 4.0.5 on 2022-07-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='This is a description for post', max_length=300),
            preserve_default=False,
        ),
    ]
