# Generated by Django 4.0 on 2022-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=250, verbose_name='News Title')),
                ('description', models.CharField(max_length=400, verbose_name='Description')),
                ('link', models.CharField(max_length=400, verbose_name='Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('posted_on', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70, verbose_name='News Title')),
                ('content', models.TextField(default='', verbose_name='News Title')),
                ('featured_image', models.ImageField(default='', upload_to='img/featured_image')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
